[package]
name = "rust-cross"
version = "0.1.0"
edition = "2021"

# [lib]
# crate-type = ["staticlib"]
# [bin]

# crate-type = ["cdylib"]

[dependencies]
sp1-zkvm = { path = "../sp1/zkvm/entrypoint" }
serde = { version = "1.0.195", features = ["derive"] }
candle-core = "0.4.1"
# panic-halt = "0.2.0"
# panic-abort = "0.3.2"

# [profile.dev]
# panic = "abort"

# [profile.release]
# debug-assertions = false
# overflow-checks = false
# panic = "abort"
# # lto = true
# codegen-units = 1
# opt-level = "z"
# [profile.release.package.compiler_builtins]
# # The compiler-builtins crate cannot reference libcore, and it's own CI will
# # verify that this is the case. This requires, however, that the crate is built
# # without overflow checks and debug assertions. Forcefully disable debug
# # assertions and overflow checks here which should ensure that even if these
# # assertions are enabled for libstd we won't enable them for compiler_builtins
# # which should ensure we still link everything correctly.
# debug-assertions = false
# overflow-checks = false

# [profile.release.package.compiler_builtins]
# The compiler-builtins crate cannot reference libcore, and it's own CI will
# verify that this is the case. This requires, however, that the crate is built
# without overflow checks and debug assertions. Forcefully disable debug
# assertions and overflow checks here which should ensure that even if these
# assertions are enabled for libstd we won't enable them for compiler_builtins
# which should ensure we still link everything correctly.
