[package]
name = "rust-cross"
version = "0.1.0"
edition = "2021"

# [lib]
# crate-type = ["staticlib"]
# [bin]

# crate-type = ["cdylib"]

[dependencies]
sp1-zkvm = { path = "../sp1/zkvm/entrypoint" }
serde = { version = "1.0.195", features = ["derive"] }
# panic-halt = "0.2.0"
# panic-abort = "0.3.2"

# [profile.dev]
# panic = "abort"

# [profile.release]
# panic = "abort"
# # lto = true
# codegen-units = 1
# opt-level = "z"
