[package]
name = "rust-cross"
version = "0.1.0"
edition = "2021"

[dependencies]
sp1-zkvm = { path = "../sp1/zkvm/entrypoint" }
serde = { version = "1.0.195", features = ["derive"] }
candle-core = "0.4.1"
candle-nn = "0.4.1"
