[build]
# target = "riscv32im-succinct-zkvm-elf"

[target.riscv64gc-unknown-linux-gnu]
# rustflags = [
# 	"-Cpasses=loweratomic",
# 	"-Clink-arg=-e_start",
# 	"-Ctarget-feature=-c",
# 	"-C",
# 	"link-arg=-s",
# ]
rustflags = [
	"-Cpasses=loweratomic",
	"-Clinker-plugin-lto=yes",
	# "-Ctarget-feature=+crt-static",
	"-Ctarget-feature=+m",
	"-Clink-arg=-s",
]
# runner = "/usr/sysroot/lib/ld-linux-riscv64-lp64d.so.1 --library-path /usr/sysroot/lib/"
linker = "riscv64-unknown-linux-gnu-gcc"

[target.riscv64gc-unknown-linux-musl]
linker = "/home/semar/x-tools/riscv64-unknown-linux-musl/riscv64-unknown-linux-musl/bin/ld"

[target.riscv64gc-unknown-none-elf]
# linker = "/opt/riscv/bin/riscv64-unknown-elf-ld"
linker = "riscv64-unknown-elf-ld"
rustflags = [
	"-Cpasses=loweratomic",
	"-Clink-arg=-e_start",
	"-Ctarget-feature=-c",
	"-Ctarget-feature=+crt-static",
	"-Clink-arg=-s",
	# 	"-C",
	# 	"link-arg=-lgcc",
]

[target.riscv32im-succinct-zkvm-elf]
rustflags = [
	"-Cpasses=loweratomic",
	"-Clinker-plugin-lto=yes",
	"-Ctarget-feature=+crt-static",
	"-Ctarget-feature=+m",
	"-Clink-arg=-s",
]
# linker = "riscv32-unknown-elf-gcc"


[target.mips-unknown-linux-gnu]
linker = "mips-linux-gnu-ld"
rustflags = [
	"-C",
	"target-feature=+crt-static",
	"-C",
	"link-arg=-s",
	"-C",
	"target-feature=-soft-float",
]
