[build]
target = "riscv64gc-unknown-linux-gnu"
# rustflags = ["-C", "embed-bitcode=yes"]

[target.riscv64gc-unknown-linux-gnu]
rustflags = [
	# 	# "-C",
	# 	# "link-arg=-Tmemory.x",
	# 	# "-C",
	# 	# "link-arg=-Tlink.x",
	"-C",
	"target-feature=+crt-static",
	"-C",
	"link-arg=-s",
	# "-C",
	# "target-feature=+m",

	# "-L",
	# "/home/semar/Work/rust-cross/buildroot/output/target/lib/",
	"-L",
	"/usr/sysroot",
	"-L",
	"/usr/sysroot/lib",

	# "-L",
	# "link-search=/home/semar/Work/rust-cross/buildroot/output/target/lib/",
	"-L",
	"link-search=/usr/sysroot",
	"-L",
	"link-search=/usr/sysroot/lib",
]
# runner = "/usr/sysroot/lib/ld-linux-riscv64-lp64d.so.1 --library-path /usr/sysroot/lib/"
linker = "riscv64-unknown-linux-gnu-ld"

[target.riscv64gc-unknown-linux-musl]
# linker = "/home/semar/Work/rust-cross/buildroot/output/host/bin/riscv64-buildroot-linux-musl-gcc"
# linker = "/home/semar/Work/rust-cross/buildroot/output/host/bin/riscv64-buildroot-linux-musl-ld"
rustflags = [
	"-L",
	"/home/semar/Work/rust-cross/buildroot/output/host/lib/gcc/riscv64-buildroot-linux-musl/12.3.0",

	"-L",
	"/home/semar/Work/rust-cross/buildroot/output/host/riscv64-buildroot-linux-musl/sysroot/lib",

	"-C",
	"link-arg=-s",

	# "-L",
	# "link-search=/home/semar/Work/rust-cross/buildroot/output/host/lib/gcc/riscv64-buildroot-linux-musl/12.3.0",
	# "-C",
	# "link-arg=-Tmemory.x",
	# "-C",
	# "link-arg=-Tlink.x",
	"-C",
	"target-feature=-crt-static",
	"-C",
	"target-feature=+m",
	# "-C",
	# "target-feature=+softfloat",
]
# runner = "/home/semar/Work/rust-cross/riscv32-linux-musl-cross/riscv64-linux-musl-cross/riscv64-linux-musl/lib/ld-musl-riscv64.so.1 --library-path /home/semar/Work/rust-cross/riscv32-linux-musl-cross/riscv64-linux-musl-cross/riscv64-linux-musl/lib"
# linker = "/home/semar/Work/rust-cross/riscv32-linux-musl-cross/riscv64-linux-musl-cross/bin/riscv64-linux-musl-gcc"
# linker = "/home/semar/Work/rust-cross/buildroot/output_riscv/host/bin/riscv64-buildroot-linux-musl-ld"
# linker = "/home/semar/Work/rust-cross/buildroot/output/host/bin/riscv64-buildroot-linux-musl-gcc"
# rustflags = [
# 	# "-C",
# 	# "target-feature=+crt-static",
# 	"-C",
# 	"link-arg=-s",
# 	# # "-C",
# 	# "-L",
# 	# "/home/semar/Work/rust-cross/buildroot/output/target/lib/",
# 	"-L",
# 	"/home/semar/Work/rust-cross/buildroot/output_riscv/staging",
# 	# "-L",
# 	# "link-search=/home/semar/Work/rust-cross/buildroot/output/target/lib/",
# 	# "-L",
# 	# "link-search=/home/semar/Work/rust-cross/buildroot/output/host/riscv64-buildroot-linux-musl/sysroot",
# 	# "link-search=/home/semar/Work/rust-cross/buildroot/output/target/lib/",
# 	# "-C",
# 	# "link-self-contained=yes",
# ]

[target.riscv32im-succinct-zkvm-elf]
rustflags = [
	# "-C",
	# "link-arg=-Tmemory.x",
	# "-C",
	# "link-arg=-Tlink.x",
	"-C",
	"target-feature=+crt-static",
	"-C",
	"target-feature=+m",
	"-C",
	"link-arg=-s",
]
# runner = "/usr/sysroot/lib/ld-linux-riscv32-lp32.so.1 --library-path /usr/sysroot/lib/"
linker = "riscv32-unknown-elf-gcc"


[target.mips-unknown-linux-gnu]
# runner = "/usr/sysroot/lib/ld-linux-riscv64-lp64d.so.1 --library-path /usr/sysroot/lib/"
linker = "mips-linux-gnu-ld"
# linker = "mips-linux-gnu-gcc"
# linker = "/home/semar/Work/rust-cross/buildroot_mips/output/host/bin/mips-linux-ld"
# rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=-s"]
rustflags = [
	"-C",
	"target-feature=+crt-static",
	"-C",
	"link-arg=-s",
	"-C",
	# "target-feature=+soft-float",
	"target-feature=-soft-float",
	# "-L",
	# "/home/semar/Work/rust-cross/buildroot/output_mips/host",
	# "-L",
	# "/home/semar/Work/rust-cross/buildroot/output_mips/staging",
]

[target.mips-unknown-linux-musl]
# ar = "/home/semar/Work/rust-cross/buildroot/output_mips/host/bin/mips-buildroot-linux-musl-ar"
# linker = "/home/semar/Work/rust-cross/buildroot/output_mips/host/bin/mips-buildroot-linux-musl-ld"
# linker = "/home/semar/Work/rust-cross/buildroot/output/host/bin/mips-buildroot-linux-musl-gcc"
# linker = "/home/semar/Work/rust-cross/buildroot/output_mips/host/bin/mips-buildroot-linux-musl-gcc"
linker = "/home/semar/Work/rust-cross/buildroot/output/host/bin/mips-buildroot-linux-musl-gcc"
rustflags = [
	"-L",
	"buildroot/output/host/lib/gcc/mips-buildroot-linux-musl/12.3.0",
	"-C",
	"target-feature=+crt-static",
	"-C",
	"link-arg=-s",
	"-C",
	"target-feature=-soft-float",
	"-C",
	"link-arg=-static-libgcc",
	"-C",
	"embed-bitcode=yes",
	"-L",
	"link-arg=-static-libgcc",
	# "target-feature=+soft-float",
	# "-C",
	# "link-self-contained=yes",
	# "-C",
	# "static",
]
# 	"-C",
# 	"link-arg=-s",
# 	# "-C",
# 	# "-C",
# 	# "link-self-contained=yes",
# ]

[target.mips-musl]
# ar = "/home/semar/Work/rust-cross/buildroot/output_mips/host/bin/mips-buildroot-linux-musl-ar"
# linker = "/home/semar/Work/rust-cross/buildroot/output_mips/host/bin/mips-buildroot-linux-musl-ld"
# linker = "/home/semar/Work/rust-cross/buildroot/output/host/bin/mips-buildroot-linux-musl-gcc"
# linker = "/home/semar/Work/rust-cross/buildroot/output_mips/host/bin/mips-buildroot-linux-musl-gcc"
linker = "/home/semar/Work/rust-cross/buildroot/output/host/bin/mips-buildroot-linux-musl-gcc"
rustflags = [
	"-L",
	"buildroot/output/host/lib/gcc/mips-buildroot-linux-musl/12.3.0",
	"-C",
	"target-feature=+crt-static",
	"-C",
	"link-arg=-s",
	"-C",
	"target-feature=-soft-float",
	"-C",
	"link-arg=-static-libgcc",
	"-C",
	"embed-bitcode=yes",
	"-L",
	"link-arg=-static-libgcc",
	# "target-feature=+soft-float",
	# "-C",
	# "link-self-contained=yes",
	# "-C",
	# "static",
]
# 	"-C",
# 	"link-arg=-s",
# 	# "-C",
# 	# "-C",
# 	# "link-self-contained=yes",
# ]
