[build]
# target = "riscv32im-succinct-zkvm-elf"

[target.x86_64-unknown-linux-gnu]
rustflags = [
	"-Cpasses=loweratomic",
	# "-Clinker-plugin-lto=yes",
	"-Ctarget-feature=+crt-static",
	"-Ctarget-feature=+m",
	# "-Clink-arg=-s",
]

[target.riscv32im-succinct-zkvm-elf]
rustflags = [
	"-Cpasses=loweratomic",
	# "-Clinker-plugin-lto=yes",
	"-Ctarget-feature=+crt-static",
	"-Ctarget-feature=+m",
	# "-Clink-arg=-s",
]
# linker = "riscv32-unknown-elf-gcc"
[target.riscv64im-unicorn-zkvm-elf]
rustflags = [
	"-Cpasses=loweratomic",
	# "-Clinker-plugin-lto=yes",
	"-Ctarget-feature=+crt-static",
	"-Ctarget-feature=+m",
	# "-Clink-arg=-s",
]
# linker = "riscv32-unknown-elf-gcc"


[target.mips-unknown-linux-gnu]
linker = "mips-linux-gnu-ld"
rustflags = [
	"-C",
	"target-feature=+crt-static",
	"-C",
	"link-arg=-s",
	"-C",
	"target-feature=-soft-float",
]
