[build]
target = "riscv64gc-unknown-linux-gnu"

[target.riscv64gc-unknown-linux-gnu]
rustflags = [
	# 	# "-C",
	# 	# "link-arg=-Tmemory.x",
	# 	# "-C",
	# 	# "link-arg=-Tlink.x",
	"-C",
	"target-feature=+crt-static",
	# "-C",
	# "target-feature=+m",
	# "-C",
	# "link-arg=-s",
]
runner = "/usr/sysroot/lib/ld-linux-riscv64-lp64d.so.1 --library-path /usr/sysroot/lib/"
linker = "riscv64-unknown-linux-gnu-gcc"

[target.riscv64gc-unknown-linux-musl]
rustflags = [
	# 	# "-C",
	# 	# "link-arg=-Tmemory.x",
	# 	# "-C",
	# 	# "link-arg=-Tlink.x",
	# "-C",
	# "target-feature=+crt-static",
	# "-C",
	# "target-feature=+m",
	# "-C",
	# "link-arg=-s",
]
runner = "/home/semar/Work/rust-cross/riscv32-linux-musl-cross/riscv64-linux-musl-cross/riscv64-linux-musl/lib/ld-musl-riscv64.so.1 --library-path /home/semar/Work/rust-cross/riscv32-linux-musl-cross/riscv64-linux-musl-cross/riscv64-linux-musl/lib"
linker = "/home/semar/Work/rust-cross/riscv32-linux-musl-cross/riscv64-linux-musl-cross/bin/riscv64-linux-musl-gcc"

# Needs to be run from docker - arch linux doesnt have easy access to mips-unknown-linux-gnu-gcc
[target.mips-unknown-linux-gnu.build-std]

[target.riscv32im-succinct-zkvm-elf]
rustflags = [
	# "-C",
	# "link-arg=-Tmemory.x",
	# "-C",
	# "link-arg=-Tlink.x",
	"-C",
	"target-feature=+crt-static",
	"-C",
	"target-feature=+m",
	"-C",
	"link-arg=-s",
]
# runner = "/usr/sysroot/lib/ld-linux-riscv32-lp32.so.1 --library-path /usr/sysroot/lib/"
linker = "riscv32-unknown-elf-gcc"


[target.mips-unknown-linux-gnu]
# runner = "/usr/sysroot/lib/ld-linux-riscv64-lp64d.so.1 --library-path /usr/sysroot/lib/"
# linker = "mips-linux-gnu-ld"
linker = "mips-linux-gnu-gcc"
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=-s"]

[target.mips-unknown-linux-musl]
linker = "/home/semar/Work/rust-cross/buildroot/output/host/bin/mips-buildroot-linux-musl-ld"
# linker = "/home/semar/Work/rust-cross/buildroot/output/host/bin/mips-buildroot-linux-musl-gcc"
rustflags = [
	"-C",
	"target-feature=+crt-static",
	"-C",
	"link-arg=-s",
	# "-C",
	"-L",
	"/home/semar/Work/rust-cross/buildroot/output/target/lib/",
	# "link-search=/home/semar/Work/rust-cross/buildroot/output/target/lib/",
	# "-C",
	# "link-self-contained=yes",
]
# rustc-flags = "-L /home/semar/Work/rust-cross/buildroot/output/target/lib/"
[target.mips-unknown-linux-musl.build-std]

# [target.mips-unknown-linux-musl.build-std]
# [unstable]
# build-std = ["panic_abort", "std"]
